In [2]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd

# 붓꽃 데이터 세트를 로딩한다.
iris = load_iris()

# iris.data는 Iris 데이터 세트에서 피처 만으로 된 데이터를 numpy로 가지고 온다.
iris_data = iris.data

# iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있다.
iris_label = iris.target
print('iris target 값: ', iris_label)
print('iris target 명: ', iris.target_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환한다.
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

print(X_test)

iris target 값:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명:  ['setosa' 'versicolor' 'virginica']
[[6.8 3.  5.5 2.1]
 [6.7 3.  5.2 2.3]
 [6.3 2.8 5.1 1.5]
 [6.3 3.3 4.7 1.6]
 [6.4 2.7 5.3 1.9]
 [4.9 3.1 1.5 0.1]
 [6.7 3.1 4.4 1.4]
 [5.7 4.4 1.5 0.4]
 [4.8 3.1 1.6 0.2]
 [6.1 2.9 4.7 1.4]
 [6.  2.2 5.  1.5]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [5.7 2.5 5.  2. ]
 [6.9 3.1 5.4 2.1]
 [4.5 2.3 1.3 0.3]
 [6.3 2.9 5.6 1.8]
 [5.6 3.  4.5 1.5]
 [6.5 3.2 5.1 2. ]
 [5.8 2.7 5.1 1.9]
 [5.6 2.5 3.9 1.1]
 [4.7 3.2 1.3 0.2]
 [4.6 3.6 1.  0.2]
 [6.4 3.2 4.5 1.5]
 [4.8 3.  1.4 0.1]
 [4.8 3.4 1.6 0.2]
 [5.9 3.  5.1 1.8]
 [6.6 3.  4.4 1.4]
 [5.4 3.9 1.3 0.4]
 [6.  3.4 4.5 1.6]]


In [3]:
# DecisionTreeClasssifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)

# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행.
pred = dt_clf.predict(X_test)

from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))


예측 정확도: 0.9333
